- src/test/groovy/io/seqera/wave/controller/ContainerTokenControllerTest.groovy
this pr will fix the build hash mismatch error
> build error fixed

- src/main/groovy/io/seqera/wave/service/logs/BuildLogServiceImpl.groovy
This PR will remove build success condition from store log to s3 bucket
> build success condition removed from store log to s3 bucket

- gradle/wrapper/gradle-wrapper.properties
This PR will upgrade gradle to version 8.4
> Upgrade gradle to 8.4

- docs/guide.md
This content is also included already for the CLI.
- https://github.com/seqeralabs/nf-tower-docs/issues/477
> Add visibility into API rate limits

- docs.sh
@pditommaso 
Updates the preview script.
> Use cr.seqera.io/public/docs-previewer image

- build.gradle
This is a minor change to correct the annotations processing package in build.gradle
> corrected annotations processing package

- docs/guide.md
- https://github.com/seqeralabs/docs/pull/48
> Copy back copy edits

- src/main/groovy/io/seqera/wave/service/persistence/WaveContainerRecord.groovy
- src/test/groovy/io/seqera/wave/service/persistence/WaveContainerRecordTest.groovy
This PR will solve the issue of NONE in timestamp field in wave_request db table.
> added OffsetDateTime.now() as default value of ts in WaveContainerRecord when timestamp in SubmitContainerTokenRequest is null

- src/main/groovy/io/seqera/wave/service/persistence/WaveContainerRecord.groovy
- src/test/groovy/io/seqera/wave/service/persistence/WaveContainerRecordTest.groovy
- src/test/groovy/io/seqera/wave/service/persistence/impl/SurrealPersistenceServiceTest.groovy
This PR will solve the Jackson deserialization issue of fusionVersion Object
> Change fusionVersion Type to String

- docs/api.md
This PR will add documentation of metrics API in  https://github.com/seqeralabs/wave/blob/master/docs/api.md
> Add documentation for Metrics API

- src/main/groovy/io/seqera/wave/core/ContainerAugmenter.groovy
- src/test/groovy/io/seqera/wave/core/ContainerAugmenterTest.groovy
This PR will change the current functionality of creating entrypoint, instead of only using the first value of the input list, it will join all the values in list
> Add all values to entrypoint

- src/main/resources/io/seqera/wave/container-view.hbs
This PR will improve the display of token cache eviction status
> Improved token cache eviction status design

- src/test/groovy/io/seqera/wave/test/RedisTestContainer.groovy
This PR will fix the flaky test related to redis container happeing in CI
> Fixed RedisTestContainer flaky test

- src/main/groovy/io/seqera/wave/service/pairing/PairingServiceImpl.groovy
- src/test/groovy/io/seqera/wave/service/pairing/PairingServiceTest.groovy
This PR patches the endpoints used by the Seqera platform during the migration phase
> Patched tower endpoints to new ones

- docs/api.md
This PR will add documentation for build status and examples for container endpoint in api.md
> Document build status and examples for container endpoint

- src/main/groovy/io/seqera/wave/controller/MetricsController.groovy
- src/main/groovy/io/seqera/wave/controller/ValidateController.groovy
- src/main/groovy/io/seqera/wave/service/pairing/socket/PairingWebSocket.groovy
This PR adds the use of the IO executor in the missing controllers
> Use IO executor consistently

- src/main/groovy/io/seqera/wave/tower/client/connector/TowerConnector.groovy
- src/main/groovy/io/seqera/wave/util/ContainerHelper.groovy
- src/test/groovy/io/seqera/wave/util/ContainerHelperTest.groovy
This PR fixes the handling of Pip packages name with Conda
> Fix the handling of pip packages with Conda

- src/main/groovy/io/seqera/wave/WaveDefault.groovy
- src/main/groovy/io/seqera/wave/controller/ContainerController.groovy
- src/test/groovy/io/seqera/wave/controller/ContainerControllerTest.groovy
This PR improves the check for pairing record connection
> Improve pairing record check

- docs/guide.mdx
This PR will fix the rate limit docs issue pointed by @ewels
> fixed rate limit docs

- .github/workflows/build.yml
- src/main/groovy/io/seqera/wave/service/builder/BuildRequest.groovy
This PR will do the following:
1. Remove unused imports in build request class
2. ~~remove .trivy-cache in build ci~~
> removed unused imports

- docs/metrics.mdx
- docs/sidebar.json
This fixes a build failure and adds to the sidebar.
> Cleanup metrics docs

- src/main/groovy/io/seqera/wave/service/metric/impl/MetricsServiceImpl.groovy
This PR will change ORF_DATE_KEY_PATTERN to ORG_DATE_KEY_PATTERN
> fix metric key pattern variable name

- docs/api.mdx
This PR will update the metrics APi documentation to add the new aggregated metrics responses
> Update metrics API documentation

- src/main/groovy/io/seqera/wave/core/RegistryProxyService.groovy
- src/main/groovy/io/seqera/wave/tower/client/TowerClient.groovy
- src/main/resources/application.yml
- src/test/groovy/io/seqera/wave/tower/client/TowerClientHttpTest.groovy
This PR fixes a potential deadlock in the caching of client methods. Solves #546
> Fix client cache deadlock

- src/main/resources/application.yml
- src/test/groovy/io/seqera/wave/service/builder/DockerBuildStrategyTest.groovy
- src/test/groovy/io/seqera/wave/service/builder/KubeBuildStrategyTest.groovy
- src/test/groovy/io/seqera/wave/service/inspect/ContainerInspectServiceImplTest.groovy
This PR bumps the use of Buildkit 0.14.1
> Bump buildkit 0.14.1

- .codespellignore
- docs/api.mdx
This PR will update the metric response in documentation to reflect the latest changes
> update mertics response

- docs/index.mdx
> Update Wave docs to include licensing note

- src/main/groovy/io/seqera/wave/service/blob/impl/KubeTransferStrategy.groovy
- src/main/groovy/io/seqera/wave/service/builder/KubeBuildStrategy.groovy
- src/main/groovy/io/seqera/wave/service/k8s/K8sService.groovy
- src/main/groovy/io/seqera/wave/service/k8s/K8sServiceImpl.groovy
- src/main/groovy/io/seqera/wave/service/scan/KubeScanStrategy.groovy
- src/test/groovy/io/seqera/wave/service/blob/impl/KubeTransferStrategyTest.groovy
Simplify K8s service api removing the need for container name
> 475 use k8s job instead of pod for blob cache transfer v2

- docs/index.mdx
> Updated Wave license note

- src/main/groovy/io/seqera/wave/core/ContainerAugmenter.groovy
This PR improve the error reporting when a specific platform cannot be found in the container manifest. 
Solve https://github.com/seqeralabs/wave/issues/578
> Improve error report

- docs/get-started.mdx
> Fix docs link

- docs/nextflow.mdx
Should work now.
cc @llewellyn-sl
> Links to Platform docs must be external to resolve

- src/main/groovy/io/seqera/wave/controller/ViewController.groovy
- src/main/resources/io/seqera/wave/container-view.hbs
This PR adds the following metadata to the container view page:
- build id 
- build cached
- freeze mode 
- fusion version
> Improve container view page

- src/main/groovy/io/seqera/wave/controller/ContainerController.groovy
- src/test/groovy/io/seqera/wave/controller/ContainerControllerTest.groovy
This PR will add /v1alpha2/container/{token}
> added /v1alpha2/container/{token}

- typespec/models/User.tsp
- typespec/models/WaveContainerRecord.tsp
- typespec/models/models.tsp
- typespec/routes.tsp
This PR will add GET /v1alpha2/container/{token} in typespec
> added GET /v1alpha2/container/{token} in typespec

- docs/get-started.mdx
This PR will replace faker example for Seqera container with samtools
> added bioinf example in docs

- src/main/groovy/io/seqera/wave/service/data/stream/impl/RedisMessageStream.groovy
- src/main/groovy/io/seqera/wave/service/job/JobQueue.groovy
- src/test/groovy/io/seqera/wave/controller/BuildControllerTest.groovy
- src/test/groovy/io/seqera/wave/controller/CustomImageControllerTest.groovy
- src/test/groovy/io/seqera/wave/controller/ErrorHandlingTest.groovy
- src/test/groovy/io/seqera/wave/controller/RegistryControllerLocalTest.groovy
- src/test/groovy/io/seqera/wave/controller/RegistryControllerPullLimitTest.groovy
- src/test/groovy/io/seqera/wave/controller/RegistryControllerRedisTest.groovy
- src/test/groovy/io/seqera/wave/controller/ViewControllerTest.groovy
- src/test/groovy/io/seqera/wave/memstore/range/RedisRangeProviderTest.groovy
- src/test/groovy/io/seqera/wave/proxy/ProxyClientWithLocalRegistryTest.groovy
- src/test/groovy/io/seqera/wave/ratelimit/SpillwayRedisRateLimiterTest.groovy
- src/test/groovy/io/seqera/wave/ratelimit/SpillwayRegistryControllerTest.groovy
- src/test/groovy/io/seqera/wave/service/builder/BuildCacheStoreRedisTest.groovy
- src/test/groovy/io/seqera/wave/service/cache/impl/RedisCacheProviderTest.groovy
- src/test/groovy/io/seqera/wave/service/counter/impl/RedisCounterProviderTest.groovy
- src/test/groovy/io/seqera/wave/service/metric/MetricsCounterStoreRedisTest.groovy
- src/test/groovy/io/seqera/wave/test/DockerRegistryContainer.groovy
- src/test/groovy/io/seqera/wave/test/RedisTestContainer.groovy
- src/test/groovy/io/seqera/wave/tower/auth/JwtTimeRedisTest.groovy
This PR simplifies and normalise of tests
> Simplify tests

- src/main/groovy/io/seqera/wave/configuration/HttpClientConfig.groovy
- src/main/groovy/io/seqera/wave/util/Retryable.groovy
- src/test/groovy/io/seqera/wave/util/RetryableTest.groovy
This PR fixed the retry multiplier setting that was not applied as expected
> Fix Retry policy delay multiplier

- src/main/groovy/io/seqera/wave/service/k8s/K8sService.groovy
- src/main/groovy/io/seqera/wave/service/k8s/K8sServiceImpl.groovy
- src/test/groovy/io/seqera/wave/service/k8s/K8sServiceImplTest.groovy
This PR fixes the detection of job status that can have one or more failed pods and still some active pods.
> Fix K8s job status detection

- src/main/groovy/io/seqera/wave/controller/ViewController.groovy
- src/main/groovy/io/seqera/wave/service/persistence/PersistenceService.groovy
- src/main/groovy/io/seqera/wave/service/persistence/WaveScanRecord.groovy
- src/main/groovy/io/seqera/wave/service/scan/ContainerScanServiceImpl.groovy
- src/main/groovy/io/seqera/wave/service/scan/ScanResult.groovy
- src/main/resources/io/seqera/wave/scan-view.hbs
- src/test/groovy/io/seqera/wave/controller/ScanControllerTest.groovy
- src/test/groovy/io/seqera/wave/controller/ViewControllerTest.groovy
- src/test/groovy/io/seqera/wave/service/persistence/WaveScanRecordTest.groovy
- src/test/groovy/io/seqera/wave/service/persistence/impl/SurrealPersistenceServiceTest.groovy
- src/test/groovy/io/seqera/wave/service/scan/ContainerScanServiceImplTest.groovy
- src/test/groovy/io/seqera/wave/service/scan/ScanResultTest.groovy
This PR will add containerImage in scan view and API
view:
API:
> added containerImage in scan

- src/main/resources/application.yml
This PR bumps trivy to version 0.55.0
> Bump trivy 0.55

- typespec/models/WaveScanRecord.tsp
This PR update the scan model adding the `containerImage`
> Update scan model

- src/main/groovy/io/seqera/wave/configuration/BlobCacheConfig.groovy
- src/main/groovy/io/seqera/wave/service/blob/impl/BlobCacheServiceImpl.groovy
- src/test/groovy/io/seqera/wave/service/blob/impl/BlobCacheServiceImplTest2.groovy
This PR change the `failureDuration` timeout to make sure is longer than the status delay
> Fix failure duration

- src/main/groovy/io/seqera/wave/service/blob/BlobCacheInfo.groovy
- src/main/groovy/io/seqera/wave/service/blob/BlobStore.groovy
- src/main/groovy/io/seqera/wave/service/blob/impl/BlobCacheServiceImpl.groovy
- src/main/groovy/io/seqera/wave/service/blob/impl/BlobCacheStore.groovy
- src/test/groovy/io/seqera/wave/service/blob/BlobCacheInfoTest.groovy
- src/test/groovy/io/seqera/wave/service/blob/impl/BlobCacheServiceImplTest2.groovy
- src/test/groovy/io/seqera/wave/service/blob/impl/BlobCacheStoreImplTest.groovy
Improve the BlobCacheInfo model with a state attribute
> Improve blob cache info

- src/test/groovy/io/seqera/wave/controller/ViewControllerTest.groovy
> fix-inspect-test

- src/main/groovy/io/seqera/wave/service/persistence/WaveBuildRecord.groovy
This PR will fix the compile error present in master branch
> fixed compile error

- src/main/groovy/io/seqera/wave/controller/InspectController.groovy
- src/main/groovy/io/seqera/wave/controller/ViewController.groovy
- src/main/groovy/io/seqera/wave/service/inclusion/ContainerInclusionImpl.groovy
- src/main/groovy/io/seqera/wave/service/inspect/ContainerInspectService.groovy
- src/main/groovy/io/seqera/wave/service/inspect/ContainerInspectServiceImpl.groovy
- src/test/groovy/io/seqera/wave/controller/InspectControllerTest.groovy
- src/test/groovy/io/seqera/wave/controller/ViewControllerTest.groovy
- src/test/groovy/io/seqera/wave/service/inclusion/ContainerInclusionImplTest.groovy
This PR will add a platform option in inspect API to get the correct details about a multi-arch container
> Improve inspect for multi platform container images

- src/main/groovy/io/seqera/wave/service/inspect/ContainerInspectServiceImpl.groovy
- src/test/groovy/io/seqera/wave/service/builder/ContainerBuildServiceTest.groovy
This PR fixes the container repository credentials check for default (docker.io) registry
> Fix repository creds check

- src/main/groovy/io/seqera/wave/util/JacksonHelper.groovy
- src/main/groovy/io/seqera/wave/util/SimplePool.groovy
- src/test/groovy/io/seqera/wave/util/SimplePoolTest.groovy
This PR improves the handling of Jackson mappers using an objects pool
> Add better pool handling for Jackson mapper objects

- typespec/models/BuildStatusResponse.tsp
- typespec/models/ContainerMirrorResponse.tsp
- typespec/models/ContainerPlatform.tsp
- typespec/models/Status.tsp
- typespec/models/models.tsp
- typespec/routes.tsp
This PR will add type spec for wave container mirroring
> Added type spec for container mirror 

- typespec/routes.tsp
This PR will fix container mirror typespec
> fix mirror typespec

- typespec/models/ContainerRequest.tsp
- typespec/models/ContainerResponse.tsp
- typespec/models/ContainerStatus.tsp
- typespec/models/ContainerStatusResponse.tsp
- typespec/models/ScanLevel.tsp
- typespec/models/ScanMode.tsp
- typespec/models/models.tsp
- typespec/routes.tsp
This PR will add typespec for container mirror and status
> Added Typespec for container mirror and status

- src/main/groovy/io/seqera/wave/service/persistence/impl/SurrealPersistenceService.groovy
this PR will fix Deserialization exception on WaveScanRecord
> fixed Deserialization exception on WaveScanRecord

- src/main/groovy/io/seqera/wave/controller/ViewController.groovy
- src/main/resources/io/seqera/wave/container-view.hbs
This PR will fix the alignment between build, scan and mirror section of container view
> fixed container view

- src/main/groovy/io/seqera/wave/core/ContainerAugmenter.groovy
- src/main/groovy/io/seqera/wave/service/builder/FreezeServiceImpl.groovy
- src/main/groovy/io/seqera/wave/service/inspect/ContainerInspectService.groovy
- src/main/groovy/io/seqera/wave/service/inspect/ContainerInspectServiceImpl.groovy
- src/test/groovy/io/seqera/wave/service/builder/FreezeServiceImplTest.groovy
- src/test/groovy/io/seqera/wave/service/inspect/ContainerInspectServiceImplTest.groovy
This PR fixes the propagation of requested container platform when determining the container entry point in a Fusion build.
> Propagate container platform with freeze

- src/main/groovy/io/seqera/wave/controller/ViewController.groovy
- src/main/resources/io/seqera/wave/build-view.hbs
- src/test/groovy/io/seqera/wave/controller/ViewControllerTest.groovy
This PR adds a link to the inspect view in the build page
> Add link to inspect from build view

- src/main/resources/io/seqera/wave/inspect-view.hbs
This PR will change the plus array for an empty to disable icon
> fixed empty array plus icon

- src/main/groovy/io/seqera/wave/controller/ViewController.groovy
- src/main/resources/io/seqera/wave/build-list.hbs
- src/test/groovy/io/seqera/wave/controller/ViewControllerTest.groovy
This PR will improve the build history view as per https://github.com/seqeralabs/wave/issues/700
> Improve build history view

- src/main/resources/io/seqera/wave/inspect-view.hbs
Annotations is a Map, so i added a length check for object type too, previously it was added only for arrays
> fixed inspect view

- .github/workflows/security-submit-dependecy-graph.yml
Created a Github Action to generate and submit the dependency graph to Github to get dependabot alerts.
> GHA to submit dependency graph to Github

- src/main/groovy/io/seqera/wave/controller/ViewController.groovy
- src/main/resources/io/seqera/wave/scan-view.hbs
- src/test/groovy/io/seqera/wave/controller/ViewControllerTest.groovy
This PR will add the following:
> added scan color for different vuls

- build.gradle
- buildSrc/src/main/groovy/io.seqera.wave.java-library-conventions.gradle
> Bump spillway 3.0.0

- src/main/groovy/io/seqera/wave/service/k8s/K8sService.groovy
- src/main/groovy/io/seqera/wave/service/k8s/K8sServiceImpl.groovy
- src/test/groovy/io/seqera/wave/service/blob/impl/KubeTransferStrategyTest.groovy
- src/test/groovy/io/seqera/wave/service/k8s/K8sServiceImplTest.groovy
This PR removes deprecated K8s methods
> Remove deprecated K8s methods

- build.gradle
> Bump jedis 5.1.3

- src/main/groovy/io/seqera/wave/controller/ValidateController.groovy
- src/test/groovy/io/seqera/wave/controller/ValidateCredsControllerTest.groovy
This PR will add /v1alpha2/validate-creds with @body
> added /v1alpha2/validate-creds

- typespec/routes.tsp
This PR will add /v1alpha2/validate-creds in Typespec
> added /v1alpha2/validate-creds in Typespec

- src/main/groovy/io/seqera/wave/service/data/queue/AbstractMessageQueue.groovy
- src/test/groovy/io/seqera/wave/service/data/queue/AbstractMessageQueueLocalTest.groovy
- src/test/groovy/io/seqera/wave/service/data/queue/AbstractMessageQueueRedisTest.groovy
This PR fixes possible raise of NPE exception while initialising `PairingOutboundQueue` class.  
Solves https://github.com/seqeralabs/wave/issues/769
> Fix NPE while creating PairingOutboundQueue

- src/main/resources/io/seqera/wave/inspect-view.hbs
This PR will do the following:
1. Add the  "Image name" row in rendered table (before "digest")
2. Expand by default all tree nodes (including "Platform) 
3. Fix the inspect link when be the image uses a tag
> improved inspect view

- build.gradle
This PR will solve https://github.com/advisories/GHSA-pr98-23f8-jwxv
> update ch.qos.logback:logback-classic from 1.15.3 to 1.5.16

- src/main/groovy/io/seqera/wave/controller/ViewController.groovy
- src/test/groovy/io/seqera/wave/controller/ViewControllerTest.groovy
This PR will change  /view/scans to post
`curl --location 'http://localhost:9090/view/scans' \
--header 'Content-Type: application/json' \
--data 'ubuntu'
`
cc @fntlnz @gavinelder
> Change /view/scans to post

- .github/workflows/build.yml
Adds permissions to use automatic token provisioning vs manually created PAT tokens.n
Docs: 
https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication
https://arc.net/l/quote/tjydcflb
> Release gha

- src/main/groovy/io/seqera/wave/service/k8s/K8sServiceImpl.groovy
- src/test/groovy/io/seqera/wave/service/k8s/K8sServiceImplTest.groovy
This PR adds the support for CPU and memory limits
> Add support for cpu and mem limits

- src/main/resources/application-dev-k8s.yml
This PR will add dns servers in dev-k8s env
> added dns servers

- .github/workflows/build-singularity.yml
This PR will update credentials for public.cr.seqera.io
> updated creds for public.cr.seqera.io

- src/main/resources/application-prometheus.yml
This pr will expose jdbc metrics to prometheus
> added jdbc binder for promethues matrics

- src/main/groovy/io/seqera/wave/service/persistence/migrate/DataMigrationService.groovy
Refactor using the same migration method for all tables
> Refactor data migration

- docs/install/docker-compose.md
in the Docker compose install guide
> Fixing a misspelling

- src/main/resources/io/seqera/wave/build-view.hbs
- src/main/resources/io/seqera/wave/mirror-view.hbs
- src/main/resources/io/seqera/wave/scan-view.hbs
Found some more bugs in views in dev
thos pr will fix them
> fixed views

- docs/configuration.md
This fill fix the metrics config docs.
we only provide per org and date for now
and also added the link for it.
> fixed metrics config docs
