- docs/sidebar.json
This rolls up the CLI index into the category itself. This simplifies the sidebar and uses space more efficiently.
> Simplify sidebar slightly

- src/main/groovy/io/seqera/wave/configuration/BuildConfig.groovy
As discussed in https://github.com/seqeralabs/wave/pull/360#discussion_r1444497611
for clarity, changing the default public repo config property to wave.build.public.repo
> Changed wave.build.public to wave.build.public-repo

- .github/workflows/build.yml
This PR fixes a CI problem, where CI workflows on push would be skipped if the branch contains slashes in its name, e.g. `update/feature`. 
@bebosudo (thank you!)  and I were able to identify the root cause of what were mysterious CI skips on push I was experiencing, which other people, for instance Munish, were not experiencing. They were indeed due to different habits in branch naming.
Reference Github doc page for single vs double asterisk in GH workflows: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
> build ci: accept slash in branch name

- src/main/groovy/io/seqera/wave/configuration/SpackConfig.groovy
- src/main/resources/io/seqera/wave/spack/spack-builder-dockerfile.txt
- src/main/resources/io/seqera/wave/spack/spack-builder-singularityfile.txt
- src/test/groovy/io/seqera/wave/controller/ContainerTokenControllerTest.groovy
- src/test/groovy/io/seqera/wave/service/builder/ContainerBuildServiceTest.groovy
Spack version in use for Wave is `default`, as per infrastructure design decision.
Identical to https://github.com/seqeralabs/wave/pull/354, but with signed-off commits.
> Update Spack version to `develop` (signedoff commits)

- .github/workflows/build.yml
- src/test/groovy/io/seqera/wave/controller/ContainerInspectControllerTest.groovy
- src/test/groovy/io/seqera/wave/controller/ContainerTokenControllerHttpTest.groovy
This PR will fix tests broken by new busybox docker image and update actions/upload-artifact to v4
> bumped actions/upload-artifact to v4 and fix tests

- src/main/groovy/io/seqera/wave/controller/InspectController.groovy
- src/main/groovy/io/seqera/wave/model/ContainerCoordinates.groovy
- src/test/groovy/io/seqera/wave/controller/InspectControllerTest.groovy
- src/test/groovy/io/seqera/wave/model/ContainerCoordinatesTest.groovy
This PR will fix the NPE thrown by parse method in ContainerCoordinates when path is not specified
> added null check for container image name

- src/main/groovy/io/seqera/wave/controller/MetricsController.groovy
- src/main/groovy/io/seqera/wave/service/counter/AbstractCounterStore.groovy
- src/main/groovy/io/seqera/wave/service/counter/CounterStore.groovy
- src/main/groovy/io/seqera/wave/service/counter/impl/CounterProvider.groovy
- src/main/groovy/io/seqera/wave/service/counter/impl/LocalCounterProvider.groovy
- src/main/groovy/io/seqera/wave/service/counter/impl/RedisCounterProvider.groovy
- src/main/groovy/io/seqera/wave/service/metric/MetricsService.groovy
- src/main/groovy/io/seqera/wave/service/metric/impl/MetricsServiceImpl.groovy
- src/main/groovy/io/seqera/wave/service/metric/model/GetOrgCountResponse.groovy
- src/test/groovy/io/seqera/wave/controller/MetricsControllerTest.groovy
- src/test/groovy/io/seqera/wave/service/counter/impl/LocalCounterProviderTest.groovy
- src/test/groovy/io/seqera/wave/service/counter/impl/RedisCounterProviderTest.groovy
- src/test/groovy/io/seqera/wave/service/metric/MetricsCounterStoreLocalTest.groovy
- src/test/groovy/io/seqera/wave/service/metric/MetricsCounterStoreRedisTest.groovy
- src/test/groovy/io/seqera/wave/service/metric/impl/MetricsServiceImplTest.groovy
closes https://github.com/seqeralabs/wave/issues/469
This PR will add the following
1. This PR will add a function in counterProvider to get all matching data data using hscan
2. This will add a method in metric service to get the count per org and total count
3. Add new model for the response
When no date or ord is provided then metrics endpoint will return the above
> Update metric service to get aggregated metrics 

- .github/workflows/build.yml
Recently we are getting lots of permission denied errors, when tests fails and GHA tries to upload test reports
`Error: EACCES: permission denied, scandir '/home/runner/work/wave/wave/build-workspace/.trivy-cache/trivy'`
This PR will remove the build-workspace directory before uploading the test report
related issue:
https://github.com/actions/upload-artifact/issues/192
> Fix "Error: EACCES: permission denied" in CI

- .github/workflows/build.yml
- src/test/groovy/io/seqera/wave/controller/RegistryControllerRedisTest.groovy
- src/test/groovy/io/seqera/wave/ratelimit/SpillwayRedisRateLimiterTest.groovy
- src/test/groovy/io/seqera/wave/service/builder/BuildCacheStoreRedisTest.groovy
- src/test/groovy/io/seqera/wave/service/metric/MetricsCounterStoreRedisTest.groovy
This PR will do the following
1. add sudo to delete workspace in ci
2. move jedis.flushAll() to cleanup in redis tests
> Fix CI errors

- src/main/groovy/io/seqera/wave/service/counter/impl/RedisCounterProvider.groovy
This PR will add count to force redis to scan certain number of records
> Fix aggregate metrics issue 

- src/main/groovy/io/seqera/wave/controller/ContainerController.groovy
- src/test/groovy/io/seqera/wave/controller/ContainerControllerTest.groovy
This OR fixes the Community repo name composition when namingStrategy is not specified
> Fixes the Community repo name composition when namingStrategy is not specified

- src/main/groovy/io/seqera/wave/controller/ContainerController.groovy
- src/main/groovy/io/seqera/wave/util/ContainerHelper.groovy
- src/test/groovy/io/seqera/wave/util/ContainerHelperTest.groovy
This PR fixes the endpoint validation for the legacy tower.nf hostname
> Fix legacy tower endpoint validation

- docs/cli/install.mdx
I have noticed that seqera docs does not mention homebrew option of wave-cli installation. https://docs.seqera.io/wave/cli/install
This PR will add that
> Add homebrew install doc

- src/main/groovy/io/seqera/wave/controller/ContainerController.groovy
- src/main/groovy/io/seqera/wave/core/RegistryProxyService.groovy
- src/main/groovy/io/seqera/wave/core/RoutePath.groovy
- src/main/groovy/io/seqera/wave/service/builder/DockerBuildStrategy.groovy
- src/main/groovy/io/seqera/wave/service/builder/KubeBuildStrategy.groovy
- src/test/groovy/io/seqera/wave/core/RegistryProxyServiceTest.groovy
- src/test/groovy/io/seqera/wave/core/RoutePathTest.groovy
- src/test/groovy/io/seqera/wave/proxy/ProxyClientTest.groovy
This PR fixes the retrieval of image digest for container built by Wave and hosted on private repos.
> Fix get image auth digest

- src/main/groovy/io/seqera/wave/service/aws/ObjectStorageOperationsFactory.groovy
- src/main/groovy/io/seqera/wave/service/aws/S3ClientFactory.groovy
This PR will fix the problem to use two s3clients one for cloudflare and another one for aws
> Fix multiple s3clients in wave

- src/main/groovy/io/seqera/wave/service/aws/ObjectStorageOperationsFactory.groovy
This PR will make sure to instantiate ObjectStorageOperationsFactory when buckets for log is specified
> fix null storage bucket error in build logs

- README.md
- configuration.md
- docs/api.mdx
- docs/cli/build-spack.mdx
- src/main/groovy/io/seqera/wave/configuration/SpackConfig.groovy
- src/main/groovy/io/seqera/wave/util/SpackHelper.groovy
- typespec/models/SpackOpts.tsp
This PR will deprecate the support for Spack and remove the support for it in the codebase
> Deprecate the support for Spack and remove the support for it in the codebase

- src/main/groovy/io/seqera/wave/configuration/BlobCacheConfig.groovy
- src/main/groovy/io/seqera/wave/service/blob/impl/KubeTransferStrategy.groovy
- src/main/groovy/io/seqera/wave/service/k8s/K8sService.groovy
- src/main/groovy/io/seqera/wave/service/k8s/K8sServiceImpl.groovy
- src/test/groovy/io/seqera/wave/service/blob/impl/KubeTransferStrategyTest.groovy
- src/test/groovy/io/seqera/wave/service/k8s/K8sServiceImplTest.groovy
This PR will add cleanup for completed blob transfer pods
tested in local:
```
(base) munish.chouhan@Munishs-MacBook-Pro ~ % kubectl get pods -n wave-local
NAME                        READY   STATUS    RESTARTS   AGE
transfer-b15025675b65bc93   1/1     Running   0          3s
transfer-d4cdd327859c19ba   1/1     Running   0          3s
transfer-71006a3e573a5c3a   1/1     Running   0          3s
(base) munish.chouhan@Munishs-MacBook-Pro ~ % kubectl get pods -n wave-local
NAME                        READY   STATUS    RESTARTS   AGE
transfer-71006a3e573a5c3a   1/1     Running   0          23s
transfer-1f419113e0d876a9   1/1     Running   0          2s
(base) munish.chouhan@Munishs-MacBook-Pro ~ % kubectl get pods -n wave-local
NAME                        READY   STATUS      RESTARTS   AGE …
```
> Enable Cleanup for blob transfer pods

- src/main/groovy/io/seqera/wave/service/builder/BuildCacheStore.groovy
- src/test/groovy/io/seqera/wave/controller/RegistryControllerRedisTest.groovy
This PR mitigates the issue with build timeout when the build cluster in congestioned. 
The overall idea is to double the overall build await the time, so the additional waiting scheduling time is taken into account before erroring the job build. 
This may be a stopgap solution. Another approach to be investigated is to use to extend the `BuildStrategy` to a method to check the current state of the build pod/container.
> Extend build timeout

- src/main/groovy/io/seqera/wave/configuration/BlobCacheConfig.groovy
- src/main/groovy/io/seqera/wave/service/blob/impl/BlobCacheServiceImpl.groovy
- src/main/groovy/io/seqera/wave/service/k8s/K8sServiceImpl.groovy
- src/test/groovy/io/seqera/wave/service/k8s/K8sServiceImplTest.groovy
This PR adds the ability to delete blob cache jobs automatically by using the `ttlSecondsAfterFinished` job spec. 
By default it used 10 days.
> Add delete after finish to blob cache jobs

- src/main/groovy/io/seqera/wave/service/k8s/K8sServiceImpl.groovy
This PR will change the propagation policy from background to foreground.
Here is the definition from here https://github.com/kubernetes-client/java/blob/master/kubernetes/docs/V1DeleteOptions.md:
> Whether and how garbage collection will be performed. Either this field or OrphanDependents may be set, but not both. The default policy is decided by the existing finalizer set in the metadata.finalizers and the resource-specific default policy. Acceptable values are: 'Orphan' - orphan the dependents; 'Background' - allow the garbage collector to delete the dependents in the background; 'Foreground' - a cascading policy that deletes all dependents in the foreground.
> Change k8s delete job propogation policy to foreground

- docs/cli/index.mdx
Noticed a small issue with the rate limit docs referencing images vs operation 
Note rate limits are mentioned on two pages https://docs.seqera.io/wave/guide#api-limits & https://docs.seqera.io/wave/cli#usage-limits
Could these potentially be consolidated to avoid duplication ?
> docs: Update wave rate limits

- src/main/groovy/io/seqera/wave/service/builder/BuildCacheStore.groovy
- src/main/groovy/io/seqera/wave/service/builder/BuildStore.groovy
- src/main/groovy/io/seqera/wave/service/builder/BuildStoreEntry.groovy
- src/main/groovy/io/seqera/wave/service/builder/ContainerBuildServiceImpl.groovy
- src/main/groovy/io/seqera/wave/service/job/JobFactory.groovy
- src/main/groovy/io/seqera/wave/service/job/spec/BuildJobSpec.groovy
- src/test/groovy/io/seqera/wave/controller/RegistryControllerRedisTest.groovy
- src/test/groovy/io/seqera/wave/encoder/MoshiEncodingStrategyTest.groovy
- src/test/groovy/io/seqera/wave/service/builder/BuildCacheStoreLocalTest.groovy
- src/test/groovy/io/seqera/wave/service/builder/BuildCacheStoreRedisTest.groovy
- src/test/groovy/io/seqera/wave/service/builder/FutureContainerBuildServiceTest.groovy
- src/test/groovy/io/seqera/wave/service/job/JobFactoryTest.groovy
- src/test/groovy/io/seqera/wave/service/job/spec/BuildJobSpecTest.groovy
This PR will do the following:
1. Add new class class BuildStoreEntry { BuildRequest request; BuildResult result }
2. Using it in place of BuildResult in [BuildCacheStore](https://github.com/seqeralabs/wave/blob/6f83ad4c099ad35a19cd0e332de137df892218d8/src/main/groovy/io/seqera/wave/service/builder/BuildCacheStore.groovy#L43-L43)
3. Modify BuildJobSpecto behave more similar to TransferJobSpec
4. Move the [schedulerId normalization logic](https://github.com/seqeralabs/wave/blob/6f83ad4c099ad35a19cd0e332de137df892218d8/src/main/groovy/io/seqera/wave/service/job/spec/BuildJobSpec.groovy#L64-L64) in the [JobFactory](https://github.com/seqeralabs/wave/blob/6f83ad4c099ad35a19cd0e332de137df892218d8/src/main/groovy/io/seqera/wave/service/job/JobFactory.groovy#L39-L39)
> Update Build containers via Job Manager

- src/main/groovy/io/seqera/wave/ErrorHandler.groovy
- src/main/groovy/io/seqera/wave/WaveDefault.groovy
- src/main/groovy/io/seqera/wave/auth/RegistryAuthService.groovy
- src/main/groovy/io/seqera/wave/auth/RegistryAuthServiceImpl.groovy
- src/main/groovy/io/seqera/wave/auth/RegistryLookupServiceImpl.groovy
- src/main/groovy/io/seqera/wave/auth/RegistryUtils.groovy
- src/main/groovy/io/seqera/wave/controller/ErrorController.groovy
- src/main/groovy/io/seqera/wave/controller/RegistryProxyController.groovy
- src/main/groovy/io/seqera/wave/exception/RegistryForwardException.groovy
- src/main/groovy/io/seqera/wave/exception/RegistryUnauthorizedAccessException.groovy
- src/main/groovy/io/seqera/wave/exchange/RegistryErrorResponse.groovy
- src/main/groovy/io/seqera/wave/proxy/ProxyClient.groovy
- src/main/groovy/io/seqera/wave/util/Retryable.groovy
- src/test/groovy/io/seqera/wave/auth/RegistryLookupServiceTest.groovy
- src/test/groovy/io/seqera/wave/controller/RegistryControllerLookupFailureTest.groovy
- src/test/groovy/io/seqera/wave/exchange/RegistryErrorResponseTest.groovy
This PR improves the handling of http errors reported by target registry when authorising the access to a container repository. 
More in details 
- do not retry on 429 (too many requests) error code
- forward the error response reported by target registry to the upstream client (docker)
- improve the logging of retry attempts 
- improve error handler interface
> Improve registry auth error handling

- src/main/groovy/io/seqera/wave/configuration/BuildConfig.groovy
This PR disables retry on build jobs, because it's expected they can fail due to invalid/broken  Dockerfile. Therefore it's useless to retry it
> Do not retry on build failure

- configuration.md
- s5cmd/Makefile
- src/main/resources/application.yml
This updates s5cmd image to `public.cr.seqera.io/wave/s5cmd` repository
> Use public repo for s5cmd

- src/main/groovy/io/seqera/wave/service/cleanup/CleanupConfig.groovy
- src/main/groovy/io/seqera/wave/service/cleanup/CleanupServiceImpl.groovy
- src/main/groovy/io/seqera/wave/tower/auth/JwtConfig.groovy
- src/main/groovy/io/seqera/wave/tower/auth/JwtMonitor.groovy
- src/main/groovy/io/seqera/wave/util/DurationUtils.groovy
- src/test/groovy/io/seqera/wave/service/cleanup/CleanupConfigTest.groovy
- src/test/groovy/io/seqera/wave/tower/auth/JwtConfigTest.groovy
- src/test/groovy/io/seqera/wave/util/DurationUtilsTest.groovy
This PR adds some entropy in the startup delay of JwtMonitor and CleanupService to prevent that multiple replicas run them in sync.
> Add entropy to cron services

- src/main/resources/io/seqera/wave/assets/expand-collapse.svg
- src/main/resources/io/seqera/wave/inspect-view.hbs
Minor improvements in CSS and styling for PR #619
* Encode SVG into the file, rather than including a new external asset
* Use [Inter](https://fonts.google.com/specimen/Inter) for our main font
* Use monospace fonts for technical details like name, tag, digest etc.
* Use [Roboto Mono](https://fonts.google.com/specimen/Roboto+Mono) for monospace font
* Avoid using inline CSS styling
* Set maximum width for first table column to avoid bounce when expanding tree nodes
* Minor tidying of padding and spacing
Future stuff we should do across all reports, for future PR(s):
Wanted to get this in first though for PR #619, before tackling that larger effort across all reports.
Currently looks almost identical, which was the intention. Just minor tidying here:
> Wave inspect: CSS edits

- src/main/resources/io/seqera/wave/build-view.hbs
- src/main/resources/io/seqera/wave/container-view.hbs
- src/main/resources/io/seqera/wave/mirror-view.hbs
This pr will add copy buttons and scroll bars in text areas of wave views
> Add copy button and scroll bars in views

- build.gradle
- src/main/groovy/io/seqera/wave/service/logs/BuildLogService.groovy
- src/main/groovy/io/seqera/wave/service/logs/BuildLogServiceImpl.groovy
- src/test/groovy/io/seqera/wave/service/logs/BuildLogsServiceTest.groovy
This pr will fix the exception, when there is no conda file in logs
> fixed exception when there is no conda lockfile

- src/main/groovy/io/seqera/wave/configuration/ScanConfig.groovy
- src/main/groovy/io/seqera/wave/service/cleanup/CleanupService.groovy
- src/main/groovy/io/seqera/wave/service/cleanup/CleanupServiceImpl.groovy
- src/main/groovy/io/seqera/wave/service/scan/ContainerScanServiceImpl.groovy
- src/main/groovy/io/seqera/wave/service/scan/ScanStateStore.groovy
- src/main/resources/application.yml
- src/test/groovy/io/seqera/wave/service/cleanup/CleanupServiceTest.groovy
- src/test/groovy/io/seqera/wave/service/scan/ContainerScanServiceImplTest.groovy
This PR adds Scan failure duration setting
> Add scan failure duration setting

- src/main/groovy/io/seqera/wave/configuration/ScanConfig.groovy
- src/main/groovy/io/seqera/wave/service/k8s/K8sServiceImpl.groovy
- src/main/groovy/io/seqera/wave/service/scan/DockerScanStrategy.groovy
- src/main/resources/application-dev.yml
- src/main/resources/application.yml
- src/test/groovy/io/seqera/wave/configuration/ScanConfigTest.groovy
- src/test/groovy/io/seqera/wave/service/k8s/K8sServiceImplTest.groovy
- src/test/groovy/io/seqera/wave/service/scan/DockerScanStrategyTest.groovy
This adds the ability to provide a custom environment for Trivy scan jobs. 
This allows also the use of custom Trivy DBs. See also https://github.com/aquasecurity/trivy/discussions/7668#discussioncomment-11028887
> Add ability to configure Trivy scan environment

- src/main/groovy/io/seqera/wave/configuration/ScanConfig.groovy
- src/main/groovy/io/seqera/wave/service/scan/ContainerScanServiceImpl.groovy
- src/test/groovy/io/seqera/wave/controller/ContainerControllerTest.groovy
- src/test/groovy/io/seqera/wave/controller/RegistryControllerLocalTest.groovy
- src/test/groovy/io/seqera/wave/service/CredentialsServiceTest.groovy
- src/test/groovy/io/seqera/wave/service/builder/KubeBuildStrategyTest.groovy
- src/test/groovy/io/seqera/wave/service/k8s/K8sServiceImplTest.groovy
- src/test/groovy/io/seqera/wave/service/scan/DockerScanStrategyTest.groovy
This PR upgrade MN runtime to version 4.6
> Upgrade to Micronaut 4.6

- src/main/groovy/io/seqera/wave/controller/ValidateController.groovy
- src/test/groovy/io/seqera/wave/controller/ValidateCredsControllerTest.groovy
This PR reverts the use of `@Body` annotation in the `/validate-creds` endpoint because it represents a braking change 
https://github.com/seqeralabs/wave/blob/059602cb4ba0a5cd174c84a04ad476c88cc6d7ed/src/main/groovy/io/seqera/wave/controller/ValidateController.groovy#L36-L36
when using `@Body` the post payload should be provided as 
```
{"userName":"value","password":"value","registry":"value"} 
``` 
Instead without `@Body` the payload should be 
```
{"request": {"userName":"value","password":"value","registry":"value"} }
```
> Fix creds validation endpoint

- docs/cli/index.mdx
Switched env vars around for accuracy.
> Switched env vars around

- src/main/groovy/io/seqera/wave/service/blob/impl/BlobCacheServiceImpl.groovy
- src/test/groovy/io/seqera/wave/service/blob/BlobStateStoreImplTest.groovy
This PR change the logic for checking the existence of blob cache by using S3 operation instead of HTTP head method. 
This is needed to prevent that the result of the HTTP HEAD check for a non-existing object retuning 404 (not found) is cached by the underlying caching rule as documented [here](https://developers.cloudflare.com/r2/reference/consistency/#caching). 
The of S3 API should bypass the caching layer and therefore preventing this issue.
> Check block existence with object operation

- src/main/groovy/io/seqera/wave/service/data/future/AbstractFutureStore.groovy
- src/main/resources/application.yml
This PR introduces the use of virtual threads for `AbstractFutureStore` class
> Migration to virtual threads - phase 4

- .github/workflows/seqera_docs_changelog.yml
- .gitignore
Automation to push a changelog entry into [seqeralbas](https://github.com/seqeralabs/docs)
That requires settings a PAT:
* Log into the GitHub account you want to push PRs from (with admin rights for both repos)
* Go to Settings > Developer Settings > Personal Access Tokens > Tokens (classic)
* Click Generate new token
* Select scope to push to seqeralabs/docs
* Store the PAT as `SEQERALABS_DOCS_PAT` secret in wave repo
> Workflow to sync changelog with Seqera docs

- src/main/groovy/io/seqera/wave/service/data/future/AbstractFutureStore.groovy
- src/main/groovy/io/seqera/wave/service/job/JobQueue.groovy
- src/main/groovy/io/seqera/wave/service/pairing/socket/PairingInboundStore.groovy
- src/main/groovy/io/seqera/wave/tower/client/connector/TowerConnector.groovy
- src/test/groovy/io/seqera/wave/service/data/future/AbstractFutureStoreTest.groovy
- src/test/groovy/io/seqera/wave/service/data/queue/AbstractMessageQueueLocalTest.groovy
This PR replaces the unneeded use of `volatile` with `final` declaration for class attribute definitions. 
When the object is fully constructed, all threads will see the initialized value of final fields, even without synchronization.
> Replace volatile with final

- src/main/groovy/io/seqera/wave/controller/ContainerController.groovy
- src/main/groovy/io/seqera/wave/controller/InspectController.groovy
- src/main/groovy/io/seqera/wave/controller/RegistryProxyController.groovy
- src/main/groovy/io/seqera/wave/service/UserService.groovy
- src/main/groovy/io/seqera/wave/service/UserServiceImpl.groovy
This PR removes the use of async API for `getUserByAccessToken` method since the use of virtual threads make it useless.
> Remove unneeded user async api

- typespec/models/BuildStatusResponse.tsp
- typespec/models/CondaOpts.tsp
- typespec/models/CondaPackages.tsp
- typespec/models/ContainerConfig.tsp
- typespec/models/ContainerInspectConfig.tsp
- typespec/models/ContainerInspectRequest.tsp
- typespec/models/ContainerInspectResponse.tsp
- typespec/models/ContainerLayer.tsp
- typespec/models/ContainerMirrorResponse.tsp
- typespec/models/ContainerPlatform.tsp
- typespec/models/ContainerRequest.tsp
- typespec/models/ContainerResponse.tsp
- typespec/models/ContainerStatusResponse.tsp
- typespec/models/Manifest.tsp
- typespec/models/ManifestLayer.tsp
- typespec/models/RootFS.tsp
- typespec/models/User.tsp
- typespec/models/ValidateRegistryCredsRequest.tsp
- typespec/models/Vulnerability.tsp
- typespec/models/WaveBuildRecord.tsp
- typespec/routes.tsp
This PR will add content from https://docs.seqera.io/wave/api to https://wave.seqera.io/openapi
> Wv 102 merge https docs.seqera.io wave api into openapi

- src/main/groovy/io/seqera/wave/controller/ServiceInfoController.groovy
- src/main/groovy/io/seqera/wave/filter/DenyCrawlerFilter.groovy
- src/main/groovy/io/seqera/wave/filter/FilterOrder.groovy
- src/main/groovy/io/seqera/wave/service/data/stream/MessageStream.groovy
- src/test/groovy/io/seqera/wave/controller/InspectControllerTest.groovy
- src/test/groovy/io/seqera/wave/controller/ScanControllerTest.groovy
- src/test/groovy/io/seqera/wave/controller/ServiceInfoControllerTest.groovy
This PR adds a filter that denies http request originated by a crawler bot
> Add DenyCrawlerFilter

- .github/workflows/seqera_docs_changelog.yml
When creating a PR to the Seqera docs for a changelog entry, include a link in the comment to the release in question.
> Changelog PR: Add link to release

- src/main/groovy/io/seqera/wave/configuration/JobManagerConfig.groovy
- src/main/groovy/io/seqera/wave/service/job/JobDispatcher.groovy
- src/main/groovy/io/seqera/wave/service/job/JobManager.groovy
- src/main/groovy/io/seqera/wave/service/job/JobPendingQueue.groovy
This PR refactor the jobs pending queue using a Redis stream in place of list relying on the existing `AbstractMessageStream` abstraction
> Implement pending queue as stream

- src/main/groovy/io/seqera/wave/service/data/stream/AbstractMessageStream.groovy
- src/main/groovy/io/seqera/wave/service/job/JobPendingQueue.groovy
- src/main/groovy/io/seqera/wave/service/job/JobProcessingQueue.groovy
This fixed a null pointer exception when accessing the `config.pollInterval` attribute. 
This happens because the `config` attribute is set \*after* the invocation of the super-constructor, that launches a listening process on a separate thread. 
The solution consist postponing the listener creation and launch thread after the class initialisation.
> Fix listener thread

- src/main/groovy/io/seqera/wave/configuration/BlobCacheConfig.groovy
- src/main/groovy/io/seqera/wave/configuration/MirrorConfig.groovy
This PR modifies the notation used for resources requests and limits made by mirror and blobCache service to make consistent with build and scan services
> Use uniform notation for resources requests & limits

- src/test/groovy/io/seqera/wave/service/builder/ContainerBuildServiceLiveTest.groovy
`should build & push container to quay.io` is failing regulary incearing timeout to fix it
> Increase timeout in test `should build & push container to quay.io`

- docs/cli/reference.mdx
I think that this is wrong in the docs. At least I ran a build and it used `mambaorg/micromamba:1.5.10-noble` - I can't find where this is defined in the code.
> Docs: Fix default conda base image

- src/main/resources/io/seqera/wave/build-view.hbs
There is a bug in the build view, tested in dev
Not released in prod yet
> fixed build view

- docs/install/configure-wave-build.md
The following updates the relevant build documentation guide & steps. 
The k8s config was not nested properly under the build config. 
Key items. 
- Changed `workspace` from `/build/work` -> `/build/workspace` this is more to help align terminology and a not strictly needed but helpful.
- `build.k8s.storage.mountpath` set a mount on `/build` for the pod so the directory is usable for build pods to prevent directory not found errors. 
- Added various config examples which a consumer may want to use such as resource limits / node selectors etc.
> docs: fix wave build steps
